version: '3.8'
services:
  portal_db:
    container_name: portal_db
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: secure
      POSTGRES_DB: portal
      LANG: de_DE.UTF-8
      POSTGRES_INITDB_ARGS: '--locale-provider=icu --icu-locale=de-DE'
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: portal_db_volume
        target: /var/lib/postgresql/data
          
volumes:
  portal_db_volume: