name: Docker Image build and push Backend

on:
  release:
      types: [published]
# workflow_on does not behave like expected
# We want AND-Condition and not OR-Condition
# TODO: fix it
#  workflow_run:
#    workflows: ["Build & Test"]
#    branches: [main]
#    types: 
#      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./portal-backend/Portal
        file: ./portal-backend/Portal/Portal.WebAPI/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.DOCKER_BACKEND_IMAGE_NAME }}:${{ github.event.release.tag_name }}
      
    
      
      
