name: Build and Test Frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Buld and Test with Node.js 18.x
      uses: actions/setup-node@v3
      working-directory: ./portal-frontend
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm ci
    - run: npm test -- --watch=false --browsers=ChromeHeadless
