name: Build & Test Backend

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

defaults:
  run:
    working-directory: ./portal-backend/Portal

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run Tests
      run: dotnet test --no-build --logger:nunit 2> /dev/null ||true
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        nunit_files: "./portal-backend/Portal/Portal.Core.Tests/TestResults/**/*.xml"
